[package]
name = "woolgather"
version = "0.0.1"
authors = ["Jeff Parsons <jeff@parsons.io>"]
edition = "2018"

[dependencies]
planetkit = { path = "../planetkit" }
rand = "0.6"
rand_xoshiro = "0.1"
shred = "0.7"
specs = "0.14"
slog = "2.0.4"
